/** Canonical display name for each ISO-3166-1 alpha-2 market code used in search queries. */
export const MARKET_NAMES: Record<string, string> = {
  ae: 'UAE',
  sa: 'Saudi Arabia',
  kw: 'Kuwait',
  qa: 'Qatar',
  bh: 'Bahrain',
  om: 'Oman',
  eg: 'Egypt',
  gb: 'UK',
  us: 'USA',
  ca: 'Canada',
  au: 'Australia',
  de: 'Germany',
  fr: 'France',
  nl: 'Netherlands',
  sg: 'Singapore',
  in: 'India',
  pk: 'Pakistan',
  ng: 'Nigeria',
  ke: 'Kenya',
  za: 'South Africa',
  ch: 'Switzerland',
  br: 'Brazil',
};
