import type { ResilienceDimensionId } from './_dimension-scorers.ts';

export type IndicatorSpec = {
  id: string;
  dimension: ResilienceDimensionId;
  description: string;
  direction: 'higherBetter' | 'lowerBetter';
  goalposts: { worst: number; best: number };
  weight: number;
  sourceKey: string;
  scope: 'global' | 'curated';
  cadence: 'realtime' | 'daily' | 'weekly' | 'monthly' | 'annual';
  imputation?: { type: 'absenceSignal' | 'conservative'; score: number; certainty: number };
};

export const INDICATOR_REGISTRY: IndicatorSpec[] = [
  // ── macroFiscal (3 sub-metrics) ───────────────────────────────────────────
  {
    id: 'govRevenuePct',
    dimension: 'macroFiscal',
    description: 'Government revenue as % of GDP (IMF GGR_G01_GDP_PT); fiscal capacity proxy',
    direction: 'higherBetter',
    goalposts: { worst: 5, best: 45 },
    weight: 0.5,
    sourceKey: 'economic:imf:macro:v2',
    scope: 'global',
    cadence: 'annual',
  },
  {
    id: 'debtGrowthRate',
    dimension: 'macroFiscal',
    description: 'Annual debt growth rate; rapid accumulation signals fiscal stress',
    direction: 'lowerBetter',
    goalposts: { worst: 20, best: 0 },
    weight: 0.2,
    sourceKey: 'economic:national-debt:v1',
    scope: 'global',
    cadence: 'annual',
  },
  {
    id: 'currentAccountPct',
    dimension: 'macroFiscal',
    description: 'Current account balance as % of GDP (IMF); external position vulnerability',
    direction: 'higherBetter',
    goalposts: { worst: -20, best: 20 },
    weight: 0.3,
    sourceKey: 'economic:imf:macro:v2',
    scope: 'global',
    cadence: 'annual',
  },

  // ── currencyExternal (3 sub-metrics, plus IMF inflation fallback for non-BIS) ─
  {
    id: 'fxVolatility',
    dimension: 'currencyExternal',
    description: 'Annualized BIS real effective exchange rate volatility (std-dev of monthly changes * sqrt(12)). Fallback chain when BIS absent: (1) IMF inflation + WB reserves proxy, (2) IMF inflation alone, (3) reserves alone, (4) conservative imputation.',
    direction: 'lowerBetter',
    goalposts: { worst: 50, best: 0 },
    weight: 0.6,
    sourceKey: 'economic:bis:eer:v1',
    scope: 'curated',
    cadence: 'monthly',
    imputation: { type: 'conservative', score: 50, certainty: 0.3 },
  },
  {
    id: 'fxDeviation',
    dimension: 'currencyExternal',
    description: 'Absolute deviation of latest BIS real EER from 100 (equilibrium index). Fallback chain when BIS absent: (1) IMF inflation + WB reserves proxy, (2) IMF inflation alone, (3) reserves alone, (4) conservative imputation.',
    direction: 'lowerBetter',
    goalposts: { worst: 35, best: 0 },
    weight: 0.25,
    sourceKey: 'economic:bis:eer:v1',
    scope: 'curated',
    cadence: 'monthly',
    imputation: { type: 'conservative', score: 50, certainty: 0.3 },
  },
  {
    id: 'fxReservesAdequacy',
    dimension: 'currencyExternal',
    description: 'Total reserves in months of imports (World Bank FI.RES.TOTL.MO). Supplementary metric for BIS countries (weight 0.15), primary metric alongside IMF inflation for non-BIS countries (~160 countries).',
    direction: 'higherBetter',
    goalposts: { worst: 1, best: 12 },
    weight: 0.15,
    sourceKey: 'resilience:static:*',
    scope: 'global',
    cadence: 'annual',
  },

  // ── tradeSanctions (4 sub-metrics) ────────────────────────────────────────
  {
    id: 'sanctionCount',
    dimension: 'tradeSanctions',
    description: 'OFAC sanctions entity count per country; piecewise normalization (0=100, 200+=near 0)',
    direction: 'lowerBetter',
    goalposts: { worst: 200, best: 0 },
    weight: 0.45,
    sourceKey: 'sanctions:country-counts:v1',
    scope: 'global',
    cadence: 'daily',
  },
  {
    id: 'tradeRestrictions',
    dimension: 'tradeSanctions',
    description: 'WTO trade restrictions count (IN_FORCE weighted 3x); curated reporter set',
    direction: 'lowerBetter',
    goalposts: { worst: 30, best: 0 },
    weight: 0.15,
    sourceKey: 'trade:restrictions:v1:tariff-overview:50',
    scope: 'curated',
    cadence: 'weekly',
    imputation: { type: 'conservative', score: 60, certainty: 0.4 },
  },
  {
    id: 'tradeBarriers',
    dimension: 'tradeSanctions',
    description: 'WTO trade barrier notifications count; curated reporter set',
    direction: 'lowerBetter',
    goalposts: { worst: 40, best: 0 },
    weight: 0.15,
    sourceKey: 'trade:barriers:v1:tariff-gap:50',
    scope: 'curated',
    cadence: 'weekly',
    imputation: { type: 'conservative', score: 60, certainty: 0.4 },
  },
  {
    id: 'appliedTariffRate',
    dimension: 'tradeSanctions',
    description: 'World Bank applied tariff rate, weighted mean, all products (TM.TAX.MRCH.WM.AR.ZS); 0%=free trade, 20%+=heavily restricted',
    direction: 'lowerBetter',
    goalposts: { worst: 20, best: 0 },
    weight: 0.25,
    sourceKey: 'resilience:static:{ISO2}',
    scope: 'global',
    cadence: 'annual',
  },

  // ── cyberDigital (3 sub-metrics) ──────────────────────────────────────────
  {
    id: 'cyberThreats',
    dimension: 'cyberDigital',
    description: 'Severity-weighted cyber threat count (critical=3x, high=2x, medium=1x, low=0.5x)',
    direction: 'lowerBetter',
    goalposts: { worst: 25, best: 0 },
    weight: 0.45,
    sourceKey: 'cyber:threats:v2',
    scope: 'global',
    cadence: 'daily',
  },
  {
    id: 'internetOutages',
    dimension: 'cyberDigital',
    description: 'Internet outage penalty (total=4x, major=2x, partial=1x)',
    direction: 'lowerBetter',
    goalposts: { worst: 20, best: 0 },
    weight: 0.35,
    sourceKey: 'infra:outages:v1',
    scope: 'global',
    cadence: 'realtime',
  },
  {
    id: 'gpsJamming',
    dimension: 'cyberDigital',
    description: 'GPS jamming hex penalty (high=3x, medium=1x)',
    direction: 'lowerBetter',
    goalposts: { worst: 20, best: 0 },
    weight: 0.2,
    sourceKey: 'intelligence:gpsjam:v2',
    scope: 'global',
    cadence: 'daily',
  },

  // ── logisticsSupply (3 sub-metrics) ───────────────────────────────────────
  {
    id: 'roadsPavedLogistics',
    dimension: 'logisticsSupply',
    description: 'Paved roads as % of total road network (World Bank IS.ROD.PAVE.ZS)',
    direction: 'higherBetter',
    goalposts: { worst: 0, best: 100 },
    weight: 0.5,
    sourceKey: 'resilience:static:{ISO2}',
    scope: 'global',
    cadence: 'annual',
  },
  {
    id: 'shippingStress',
    dimension: 'logisticsSupply',
    description: 'Global shipping stress score from supply-chain monitor',
    direction: 'lowerBetter',
    goalposts: { worst: 100, best: 0 },
    weight: 0.25,
    sourceKey: 'supply_chain:shipping_stress:v1',
    scope: 'global',
    cadence: 'daily',
  },
  {
    id: 'transitDisruption',
    dimension: 'logisticsSupply',
    description: 'Mean transit corridor disruption (disruptionPct + incidentCount7d * 0.5)',
    direction: 'lowerBetter',
    goalposts: { worst: 30, best: 0 },
    weight: 0.25,
    sourceKey: 'supply_chain:transit-summaries:v1',
    scope: 'global',
    cadence: 'daily',
  },

  // ── infrastructure (3 sub-metrics) ────────────────────────────────────────
  {
    id: 'electricityAccess',
    dimension: 'infrastructure',
    description: 'Access to electricity as % of population (World Bank EG.ELC.ACCS.ZS)',
    direction: 'higherBetter',
    goalposts: { worst: 40, best: 100 },
    weight: 0.4,
    sourceKey: 'resilience:static:{ISO2}',
    scope: 'global',
    cadence: 'annual',
  },
  {
    id: 'roadsPavedInfra',
    dimension: 'infrastructure',
    description: 'Paved roads as % of total road network (World Bank IS.ROD.PAVE.ZS)',
    direction: 'higherBetter',
    goalposts: { worst: 0, best: 100 },
    weight: 0.35,
    sourceKey: 'resilience:static:{ISO2}',
    scope: 'global',
    cadence: 'annual',
  },
  {
    id: 'infraOutages',
    dimension: 'infrastructure',
    description: 'Internet outage penalty (total=4x, major=2x, partial=1x); shared source with cyberDigital',
    direction: 'lowerBetter',
    goalposts: { worst: 20, best: 0 },
    weight: 0.25,
    sourceKey: 'infra:outages:v1',
    scope: 'global',
    cadence: 'realtime',
  },

  // ── energy (7 sub-metrics) ────────────────────────────────────────────────
  {
    id: 'energyImportDependency',
    dimension: 'energy',
    description: 'IEA energy import dependency (% of total energy supply from imports)',
    direction: 'lowerBetter',
    goalposts: { worst: 100, best: 0 },
    weight: 0.25,
    sourceKey: 'resilience:static:{ISO2}',
    scope: 'global',
    cadence: 'annual',
  },
  {
    id: 'gasShare',
    dimension: 'energy',
    description: 'Natural gas share of energy mix (%); high share = single-source vulnerability',
    direction: 'lowerBetter',
    goalposts: { worst: 100, best: 0 },
    weight: 0.12,
    sourceKey: 'energy:mix:v1:{ISO2}',
    scope: 'global',
    cadence: 'annual',
  },
  {
    id: 'coalShare',
    dimension: 'energy',
    description: 'Coal share of energy mix (%); high share = transition risk and pollution',
    direction: 'lowerBetter',
    goalposts: { worst: 100, best: 0 },
    weight: 0.08,
    sourceKey: 'energy:mix:v1:{ISO2}',
    scope: 'global',
    cadence: 'annual',
  },
  {
    id: 'renewShare',
    dimension: 'energy',
    description: 'Renewable energy share of energy mix (%); diversification and resilience',
    direction: 'higherBetter',
    goalposts: { worst: 0, best: 100 },
    weight: 0.05,
    sourceKey: 'energy:mix:v1:{ISO2}',
    scope: 'global',
    cadence: 'annual',
  },
  {
    id: 'gasStorageStress',
    dimension: 'energy',
    description: 'Gas storage fill stress: (80 - fillPct) / 80 clamped to [0,1], scaled to 0-100',
    direction: 'lowerBetter',
    goalposts: { worst: 100, best: 0 },
    weight: 0.1,
    sourceKey: 'energy:gas-storage:v1:{ISO2}',
    scope: 'global',
    cadence: 'daily',
  },
  {
    id: 'energyPriceStress',
    dimension: 'energy',
    description: 'Mean absolute energy price change across commodities',
    direction: 'lowerBetter',
    goalposts: { worst: 25, best: 0 },
    weight: 0.1,
    sourceKey: 'economic:energy:v1:all',
    scope: 'global',
    cadence: 'daily',
  },
  {
    id: 'electricityConsumption',
    dimension: 'energy',
    description: 'Per-capita electricity consumption (kWh/year, World Bank EG.USE.ELEC.KH.PC); low = grid collapse',
    direction: 'higherBetter',
    goalposts: { worst: 200, best: 8000 },
    weight: 0.3,
    sourceKey: 'resilience:static:{ISO2}',
    scope: 'global',
    cadence: 'annual',
  },

  // ── governanceInstitutional (6 sub-metrics, equal weight) ─────────────────
  {
    id: 'wgiVoiceAccountability',
    dimension: 'governanceInstitutional',
    description: 'World Bank WGI: Voice and Accountability (-2.5 to +2.5)',
    direction: 'higherBetter',
    goalposts: { worst: -2.5, best: 2.5 },
    weight: 1 / 6,
    sourceKey: 'resilience:static:{ISO2}',
    scope: 'global',
    cadence: 'annual',
  },
  {
    id: 'wgiPoliticalStability',
    dimension: 'governanceInstitutional',
    description: 'World Bank WGI: Political Stability and Absence of Violence (-2.5 to +2.5)',
    direction: 'higherBetter',
    goalposts: { worst: -2.5, best: 2.5 },
    weight: 1 / 6,
    sourceKey: 'resilience:static:{ISO2}',
    scope: 'global',
    cadence: 'annual',
  },
  {
    id: 'wgiGovernmentEffectiveness',
    dimension: 'governanceInstitutional',
    description: 'World Bank WGI: Government Effectiveness (-2.5 to +2.5)',
    direction: 'higherBetter',
    goalposts: { worst: -2.5, best: 2.5 },
    weight: 1 / 6,
    sourceKey: 'resilience:static:{ISO2}',
    scope: 'global',
    cadence: 'annual',
  },
  {
    id: 'wgiRegulatoryQuality',
    dimension: 'governanceInstitutional',
    description: 'World Bank WGI: Regulatory Quality (-2.5 to +2.5)',
    direction: 'higherBetter',
    goalposts: { worst: -2.5, best: 2.5 },
    weight: 1 / 6,
    sourceKey: 'resilience:static:{ISO2}',
    scope: 'global',
    cadence: 'annual',
  },
  {
    id: 'wgiRuleOfLaw',
    dimension: 'governanceInstitutional',
    description: 'World Bank WGI: Rule of Law (-2.5 to +2.5)',
    direction: 'higherBetter',
    goalposts: { worst: -2.5, best: 2.5 },
    weight: 1 / 6,
    sourceKey: 'resilience:static:{ISO2}',
    scope: 'global',
    cadence: 'annual',
  },
  {
    id: 'wgiControlOfCorruption',
    dimension: 'governanceInstitutional',
    description: 'World Bank WGI: Control of Corruption (-2.5 to +2.5)',
    direction: 'higherBetter',
    goalposts: { worst: -2.5, best: 2.5 },
    weight: 1 / 6,
    sourceKey: 'resilience:static:{ISO2}',
    scope: 'global',
    cadence: 'annual',
  },

  // ── socialCohesion (3 sub-metrics) ────────────────────────────────────────
  {
    id: 'gpiScore',
    dimension: 'socialCohesion',
    description: 'Global Peace Index score; empirical range 1.1 (Iceland) to 3.4 (Yemen 2024)',
    direction: 'lowerBetter',
    goalposts: { worst: 3.6, best: 1.0 },
    weight: 0.55,
    sourceKey: 'resilience:static:{ISO2}',
    scope: 'global',
    cadence: 'annual',
  },
  {
    id: 'displacementTotal',
    dimension: 'socialCohesion',
    description: 'UNHCR total displaced persons (log10 scale); absent = null (excluded from blend, no imputation)',
    direction: 'lowerBetter',
    goalposts: { worst: 7, best: 0 },
    weight: 0.25,
    sourceKey: 'displacement:summary:v1:{year}',
    scope: 'global',
    cadence: 'annual',
  },
  {
    id: 'unrestEvents',
    dimension: 'socialCohesion',
    description: 'Unrest event count (severity-weighted) + sqrt(fatalities)',
    direction: 'lowerBetter',
    goalposts: { worst: 20, best: 0 },
    weight: 0.2,
    sourceKey: 'unrest:events:v1',
    scope: 'global',
    cadence: 'realtime',
  },

  // ── borderSecurity (2 sub-metrics) ────────────────────────────────────────
  {
    id: 'ucdpConflict',
    dimension: 'borderSecurity',
    description: 'UCDP armed conflict metric: eventCount*2 + typeWeight + sqrt(deaths)',
    direction: 'lowerBetter',
    goalposts: { worst: 30, best: 0 },
    weight: 0.65,
    sourceKey: 'conflict:ucdp-events:v1',
    scope: 'global',
    cadence: 'realtime',
  },
  {
    id: 'displacementHosted',
    dimension: 'borderSecurity',
    description: 'UNHCR hosted/total displaced persons (log10 scale); refugee pressure proxy',
    direction: 'lowerBetter',
    goalposts: { worst: 7, best: 0 },
    weight: 0.35,
    sourceKey: 'displacement:summary:v1:{year}',
    scope: 'global',
    cadence: 'annual',
    imputation: { type: 'absenceSignal', score: 85, certainty: 0.6 },
  },

  // ── informationCognitive (3 sub-metrics) ──────────────────────────────────
  {
    id: 'rsfPressFreedom',
    dimension: 'informationCognitive',
    description: 'Reporters Sans Frontieres press freedom score (0-100)',
    direction: 'higherBetter',
    goalposts: { worst: 0, best: 100 },
    weight: 0.55,
    sourceKey: 'resilience:static:{ISO2}',
    scope: 'global',
    cadence: 'annual',
  },
  {
    id: 'socialVelocity',
    dimension: 'informationCognitive',
    description: 'Reddit social velocity score (log10(velocity+1)); viral narrative stress',
    direction: 'lowerBetter',
    goalposts: { worst: 3, best: 0 },
    weight: 0.15,
    sourceKey: 'intelligence:social:reddit:v1',
    scope: 'global',
    cadence: 'realtime',
  },
  {
    id: 'newsThreatScore',
    dimension: 'informationCognitive',
    description: 'AI news threat summary (critical=4x, high=2x, medium=1x, low=0.5x)',
    direction: 'lowerBetter',
    goalposts: { worst: 20, best: 0 },
    weight: 0.3,
    sourceKey: 'news:threat:summary:v1',
    scope: 'global',
    cadence: 'daily',
  },

  // ── healthPublicService (3 sub-metrics) ───────────────────────────────────
  {
    id: 'uhcIndex',
    dimension: 'healthPublicService',
    description: 'WHO Universal Health Coverage service coverage index (0-100)',
    direction: 'higherBetter',
    goalposts: { worst: 40, best: 90 },
    weight: 0.45,
    sourceKey: 'resilience:static:{ISO2}',
    scope: 'global',
    cadence: 'annual',
  },
  {
    id: 'measlesCoverage',
    dimension: 'healthPublicService',
    description: 'WHO measles immunization coverage among 1-year-olds (%)',
    direction: 'higherBetter',
    goalposts: { worst: 50, best: 99 },
    weight: 0.35,
    sourceKey: 'resilience:static:{ISO2}',
    scope: 'global',
    cadence: 'annual',
  },
  {
    id: 'hospitalBeds',
    dimension: 'healthPublicService',
    description: 'WHO hospital beds per 1,000 people',
    direction: 'higherBetter',
    goalposts: { worst: 0, best: 8 },
    weight: 0.2,
    sourceKey: 'resilience:static:{ISO2}',
    scope: 'global',
    cadence: 'annual',
  },

  // ── foodWater (3 sub-metrics) ─────────────────────────────────────────────
  {
    id: 'ipcPeopleInCrisis',
    dimension: 'foodWater',
    description: 'IPC/FAO people in food crisis (log10 scale)',
    direction: 'lowerBetter',
    goalposts: { worst: 7, best: 0 },
    weight: 0.45,
    sourceKey: 'resilience:static:{ISO2}',
    scope: 'global',
    cadence: 'annual',
    imputation: { type: 'absenceSignal', score: 88, certainty: 0.7 },
  },
  {
    id: 'ipcPhase',
    dimension: 'foodWater',
    description: 'IPC food crisis phase (1-5 scale)',
    direction: 'lowerBetter',
    goalposts: { worst: 5, best: 1 },
    weight: 0.15,
    sourceKey: 'resilience:static:{ISO2}',
    scope: 'global',
    cadence: 'annual',
    imputation: { type: 'absenceSignal', score: 88, certainty: 0.7 },
  },
  {
    id: 'aquastatWaterStress',
    dimension: 'foodWater',
    description: 'FAO AQUASTAT stress/withdrawal/dependency indicators (% scale 0-100)',
    direction: 'lowerBetter',
    goalposts: { worst: 100, best: 0 },
    weight: 0.25,
    sourceKey: 'resilience:static:{ISO2}',
    scope: 'global',
    cadence: 'annual',
  },
  {
    id: 'aquastatWaterAvailability',
    dimension: 'foodWater',
    description: 'FAO AQUASTAT availability/renewable/access indicators (0-100 % or 0-5000 m3/capita)',
    direction: 'higherBetter',
    goalposts: { worst: 0, best: 5000 },
    weight: 0.15,
    sourceKey: 'resilience:static:{ISO2}',
    scope: 'global',
    cadence: 'annual',
  },
];
