// Auto-generated from src/config/commodity-geo.ts — do not edit manually
const MINING_SITES = [
  {
    "id": "carlin-trend",
    "name": "Carlin Trend",
    "lat": 40.73,
    "lon": -116.12,
    "mineral": "Gold",
    "country": "USA",
    "operator": "Nevada Gold Mines (Barrick/Newmont JV)",
    "status": "producing",
    "significance": "Largest gold mining district in Western Hemisphere. ~3.5Moz/yr combined output.",
    "productionRank": "Western Hemisphere #1",
    "openPitOrUnderground": "both"
  },
  {
    "id": "super-pit",
    "name": "Super Pit (KCGM)",
    "lat": -30.784,
    "lon": 121.498,
    "mineral": "Gold",
    "country": "Australia",
    "operator": "Northern Star Resources",
    "status": "producing",
    "significance": "One of Australia's largest open-pit gold mines. ~600koz/yr.",
    "productionRank": "Australia #2",
    "openPitOrUnderground": "open-pit"
  },
  {
    "id": "boddington",
    "name": "Boddington",
    "lat": -32.795,
    "lon": 116.48,
    "mineral": "Gold",
    "country": "Australia",
    "operator": "Newmont",
    "status": "producing",
    "significance": "Australia's largest gold mine. Also significant copper by-product.",
    "productionRank": "Australia #1",
    "openPitOrUnderground": "open-pit"
  },
  {
    "id": "mponeng",
    "name": "Mponeng",
    "lat": -26.486,
    "lon": 27.445,
    "mineral": "Gold",
    "country": "South Africa",
    "operator": "AngloGold Ashanti",
    "status": "producing",
    "significance": "World's deepest gold mine (4km). High-grade underground operation.",
    "productionRank": "World deepest mine",
    "openPitOrUnderground": "underground"
  },
  {
    "id": "olimpiada",
    "name": "Olimpiada",
    "lat": 59.03,
    "lon": 93.37,
    "mineral": "Gold",
    "country": "Russia",
    "operator": "Polyus",
    "status": "producing",
    "significance": "Russia's largest gold mine, among world's top 5. Siberian deposit.",
    "productionRank": "World top 5",
    "openPitOrUnderground": "open-pit"
  },
  {
    "id": "lihir",
    "name": "Lihir",
    "lat": -3.12,
    "lon": 152.65,
    "mineral": "Gold",
    "country": "Papua New Guinea",
    "operator": "Newcrest/Newmont",
    "status": "producing",
    "significance": "Active volcanic island gold mine. ~950koz/yr.",
    "openPitOrUnderground": "open-pit"
  },
  {
    "id": "obuasi",
    "name": "Obuasi",
    "lat": 6.2,
    "lon": -1.67,
    "mineral": "Gold",
    "country": "Ghana",
    "operator": "AngloGold Ashanti",
    "status": "producing",
    "significance": "High-grade West African gold mine. Historically one of Africa's largest producers.",
    "openPitOrUnderground": "underground"
  },
  {
    "id": "pueblo-viejo",
    "name": "Pueblo Viejo",
    "lat": 19.33,
    "lon": -70.06,
    "mineral": "Gold",
    "country": "Dominican Republic",
    "operator": "Barrick Gold / Newmont JV",
    "status": "producing",
    "significance": "Largest gold mine in the Caribbean. ~800koz/yr.",
    "openPitOrUnderground": "open-pit"
  },
  {
    "id": "detour-lake",
    "name": "Detour Lake",
    "lat": 50.05,
    "lon": -79.7,
    "mineral": "Gold",
    "country": "Canada",
    "operator": "Agnico Eagle",
    "status": "producing",
    "significance": "Canada's largest open-pit gold mine by land area. ~700koz/yr.",
    "openPitOrUnderground": "open-pit"
  },
  {
    "id": "cortez",
    "name": "Cortez (Pipeline)",
    "lat": 40.26,
    "lon": -116.35,
    "mineral": "Gold",
    "country": "USA",
    "operator": "Nevada Gold Mines (Barrick)",
    "status": "producing",
    "significance": "Major Tier One gold mine in Nevada. Part of Nevada Gold Mines complex.",
    "openPitOrUnderground": "both"
  },
  {
    "id": "donlin-gold",
    "name": "Donlin Gold",
    "lat": 61.98,
    "lon": -158.08,
    "mineral": "Gold",
    "country": "USA",
    "operator": "Barrick / NovaGold JV",
    "status": "development",
    "significance": "One of the world's largest undeveloped gold deposits. Remote Alaska site.",
    "openPitOrUnderground": "open-pit"
  },
  {
    "id": "muruntau",
    "name": "Muruntau",
    "lat": 41.56,
    "lon": 64.58,
    "mineral": "Gold",
    "country": "Uzbekistan",
    "operator": "Navoi Mining & Metallurgy Combinat",
    "status": "producing",
    "significance": "World's largest open-pit gold mine by area. ~2.8Moz/yr. State-owned.",
    "productionRank": "World #2 gold mine",
    "annualOutput": "2.8 Moz/yr",
    "openPitOrUnderground": "open-pit"
  },
  {
    "id": "kibali",
    "name": "Kibali",
    "lat": 3.07,
    "lon": 29.76,
    "mineral": "Gold",
    "country": "DRC",
    "operator": "Barrick Gold / AngloGold Ashanti JV",
    "status": "producing",
    "significance": "Largest gold mine in DRC. ~800koz/yr. Underground and open-pit hybrid.",
    "annualOutput": "800 Koz/yr",
    "openPitOrUnderground": "both"
  },
  {
    "id": "sukhoi-log",
    "name": "Sukhoi Log",
    "lat": 58.29,
    "lon": 115.22,
    "mineral": "Gold",
    "country": "Russia",
    "operator": "Polyus (under development)",
    "status": "development",
    "significance": "One of the world's largest undeveloped gold deposits. Est. ~2.3Moz/yr at full capacity.",
    "annualOutput": "~2.3 Moz/yr (projected)",
    "openPitOrUnderground": "open-pit"
  },
  {
    "id": "ahafo",
    "name": "Ahafo",
    "lat": 7.06,
    "lon": -2.34,
    "mineral": "Gold",
    "country": "Ghana",
    "operator": "Newmont",
    "status": "producing",
    "significance": "Major Newmont operation in Ghana's prolific Ashanti Belt. ~800koz/yr.",
    "annualOutput": "800 Koz/yr",
    "openPitOrUnderground": "open-pit"
  },
  {
    "id": "loulo-gounkoto",
    "name": "Loulo-Gounkoto",
    "lat": 14.85,
    "lon": -11.41,
    "mineral": "Gold",
    "country": "Mali",
    "operator": "Barrick Gold",
    "status": "producing",
    "significance": "Key Barrick operation in West Africa. ~700koz/yr. Subject to Malian mining code pressure.",
    "annualOutput": "700 Koz/yr",
    "openPitOrUnderground": "underground"
  },
  {
    "id": "south-deep",
    "name": "South Deep",
    "lat": -26.52,
    "lon": 27.54,
    "mineral": "Gold",
    "country": "South Africa",
    "operator": "Gold Fields",
    "status": "producing",
    "significance": "One of the world's largest gold mines by reserves. Deep underground operation (~3km).",
    "annualOutput": "300 Koz/yr",
    "openPitOrUnderground": "underground"
  },
  {
    "id": "kumtor",
    "name": "Kumtor",
    "lat": 41.81,
    "lon": 78.19,
    "mineral": "Gold",
    "country": "Kyrgyzstan",
    "operator": "Centerra Gold (state-nationalized)",
    "status": "producing",
    "significance": "Largest gold mine in Central Asia. ~500koz/yr. Nationalized by Kyrgyzstan in 2022.",
    "annualOutput": "500 Koz/yr",
    "openPitOrUnderground": "open-pit"
  },
  {
    "id": "yanacocha",
    "name": "Yanacocha",
    "lat": -6.94,
    "lon": -78.56,
    "mineral": "Gold",
    "country": "Peru",
    "operator": "Newmont / Buenaventura / IFC JV",
    "status": "producing",
    "significance": "Largest gold mine in South America. ~400koz/yr. Transitioning to Yanacocha Sulfides project.",
    "annualOutput": "400 Koz/yr",
    "openPitOrUnderground": "open-pit"
  },
  {
    "id": "cerro-negro",
    "name": "Cerro Negro",
    "lat": -46.75,
    "lon": -67.5,
    "mineral": "Gold",
    "country": "Argentina",
    "operator": "Newmont",
    "status": "producing",
    "significance": "High-grade Patagonian gold mine. ~300koz/yr. One of the highest-grade operations globally.",
    "annualOutput": "300 Koz/yr",
    "openPitOrUnderground": "underground"
  },
  {
    "id": "tropicana",
    "name": "Tropicana",
    "lat": -29.3,
    "lon": 124.8,
    "mineral": "Gold",
    "country": "Australia",
    "operator": "AngloGold Ashanti / Regis Resources",
    "status": "producing",
    "significance": "Remote Western Australian gold mine in the Great Victoria Desert. ~500koz/yr.",
    "annualOutput": "500 Koz/yr",
    "openPitOrUnderground": "open-pit"
  },
  {
    "id": "fresnillo-mine",
    "name": "Fresnillo Mine",
    "lat": 23.17,
    "lon": -102.87,
    "mineral": "Silver",
    "country": "Mexico",
    "operator": "Fresnillo plc",
    "status": "producing",
    "significance": "World's largest primary silver mine. >50Moz/yr silver output.",
    "productionRank": "World #1 silver mine",
    "openPitOrUnderground": "underground"
  },
  {
    "id": "penasquito",
    "name": "Peñasquito",
    "lat": 25.18,
    "lon": -101.81,
    "mineral": "Silver",
    "country": "Mexico",
    "operator": "Newmont",
    "status": "producing",
    "significance": "Mexico's largest open-pit mine. World's largest silver producer by output. Gold/zinc/lead by-products.",
    "productionRank": "World #2 silver mine",
    "openPitOrUnderground": "open-pit"
  },
  {
    "id": "kghm-silver",
    "name": "KGHM Copper/Silver Complex",
    "lat": 51.62,
    "lon": 16.24,
    "mineral": "Silver",
    "country": "Poland",
    "operator": "KGHM Polska Miedź",
    "status": "producing",
    "significance": "Europe's largest copper and silver producer. World's second-largest silver producer.",
    "openPitOrUnderground": "underground"
  },
  {
    "id": "escondida",
    "name": "Escondida",
    "lat": -24.27,
    "lon": -69.07,
    "mineral": "Copper",
    "country": "Chile",
    "operator": "BHP / Rio Tinto / JECO",
    "status": "producing",
    "significance": "World's largest copper mine. ~1.2Mt Cu/yr. Atacama Desert, Chile.",
    "productionRank": "World #1 copper mine",
    "openPitOrUnderground": "open-pit",
    "productionCapacity": "1.2Mt Cu/yr"
  },
  {
    "id": "chuquicamata",
    "name": "Chuquicamata",
    "lat": -22.3,
    "lon": -68.93,
    "mineral": "Copper",
    "country": "Chile",
    "operator": "Codelco",
    "status": "producing",
    "significance": "World's largest open-pit copper mine by volume. Transitioning to underground.",
    "productionRank": "World largest open pit by volume",
    "openPitOrUnderground": "both"
  },
  {
    "id": "el-teniente",
    "name": "El Teniente",
    "lat": -34.08,
    "lon": -70.36,
    "mineral": "Copper",
    "country": "Chile",
    "operator": "Codelco",
    "status": "producing",
    "significance": "World's largest underground copper mine. ~430kt Cu/yr.",
    "productionRank": "World #1 underground copper mine",
    "openPitOrUnderground": "underground"
  },
  {
    "id": "grasberg",
    "name": "Grasberg",
    "lat": -4.05,
    "lon": 137.12,
    "mineral": "Copper",
    "country": "Indonesia",
    "operator": "Freeport-McMoRan / Inalum",
    "status": "producing",
    "significance": "World's second-largest copper mine. Also world's largest gold mine by contained gold.",
    "productionRank": "World #2 copper, #1 gold",
    "openPitOrUnderground": "underground"
  },
  {
    "id": "cerro-verde",
    "name": "Cerro Verde",
    "lat": -16.52,
    "lon": -71.6,
    "mineral": "Copper",
    "country": "Peru",
    "operator": "Freeport-McMoRan / Buenaventura / SMM",
    "status": "producing",
    "significance": "Major Peruvian copper producer. ~500kt Cu/yr.",
    "openPitOrUnderground": "open-pit"
  },
  {
    "id": "antamina",
    "name": "Antamina",
    "lat": -9.53,
    "lon": -77.04,
    "mineral": "Copper",
    "country": "Peru",
    "operator": "BHP / Glencore / Teck / Mitsubishi",
    "status": "producing",
    "significance": "World-class copper-zinc mine in the Andes. ~460kt Cu/yr.",
    "openPitOrUnderground": "open-pit"
  },
  {
    "id": "morenci",
    "name": "Morenci",
    "lat": 33.08,
    "lon": -109.36,
    "mineral": "Copper",
    "country": "USA",
    "operator": "Freeport-McMoRan",
    "status": "producing",
    "significance": "Largest copper mine in North America. ~500kt Cu/yr.",
    "productionRank": "North America #1 copper mine",
    "openPitOrUnderground": "open-pit"
  },
  {
    "id": "kamoa-kakula",
    "name": "Kamoa-Kakula",
    "lat": -5.54,
    "lon": 25.96,
    "mineral": "Copper",
    "country": "DRC",
    "operator": "Ivanhoe Mines / Zijin Mining",
    "status": "producing",
    "significance": "Highest-grade major copper mine discovered in 30 years. Fastest-growing producer.",
    "productionRank": "World #3 copper mine (growing)",
    "openPitOrUnderground": "underground"
  },
  {
    "id": "oyu-tolgoi",
    "name": "Oyu Tolgoi",
    "lat": 43,
    "lon": 107,
    "mineral": "Copper",
    "country": "Mongolia",
    "operator": "Rio Tinto / Turquoise Hill",
    "status": "producing",
    "significance": "World's third-largest copper-gold deposit. Underground expansion ramping up.",
    "openPitOrUnderground": "both"
  },
  {
    "id": "lumwana",
    "name": "Lumwana",
    "lat": -12.52,
    "lon": 25.36,
    "mineral": "Copper",
    "country": "Zambia",
    "operator": "Barrick Gold",
    "status": "producing",
    "significance": "One of Africa's largest copper mines. ~140kt Cu/yr. Major Zambian producer.",
    "openPitOrUnderground": "open-pit"
  },
  {
    "id": "greenbushes",
    "name": "Greenbushes",
    "lat": -33.86,
    "lon": 116.01,
    "mineral": "Lithium",
    "country": "Australia",
    "operator": "Talison Lithium (Albemarle / Tianqi)",
    "status": "producing",
    "significance": "World's largest hard-rock lithium mine. Highest-grade spodumene deposit.",
    "productionRank": "World #1 hard-rock lithium",
    "openPitOrUnderground": "open-pit",
    "productionCapacity": "~1.5Mt spodumene/yr"
  },
  {
    "id": "salar-atacama",
    "name": "Salar de Atacama",
    "lat": -23.5,
    "lon": -68.33,
    "mineral": "Lithium",
    "country": "Chile",
    "operator": "SQM / Albemarle",
    "status": "producing",
    "significance": "World's largest and lowest-cost lithium brine source. ~150kt LCE/yr.",
    "productionRank": "World #1 lithium brine",
    "openPitOrUnderground": "in-situ",
    "productionCapacity": "150kt LCE/yr"
  },
  {
    "id": "pilgangoora",
    "name": "Pilgangoora",
    "lat": -21.03,
    "lon": 118.91,
    "mineral": "Lithium",
    "country": "Australia",
    "operator": "Pilbara Minerals",
    "status": "producing",
    "significance": "Major hard-rock lithium mine. World's largest spodumene project after Greenbushes.",
    "openPitOrUnderground": "open-pit"
  },
  {
    "id": "olaroz",
    "name": "Olaroz",
    "lat": -23.47,
    "lon": -66.81,
    "mineral": "Lithium",
    "country": "Argentina",
    "operator": "Allkem / Toyota Tsusho",
    "status": "producing",
    "significance": "Key Argentina lithium brine operation. Part of the Lithium Triangle.",
    "openPitOrUnderground": "in-situ"
  },
  {
    "id": "cauchari-olaroz",
    "name": "Cauchari-Olaroz",
    "lat": -23.82,
    "lon": -66.89,
    "mineral": "Lithium",
    "country": "Argentina",
    "operator": "Lithium Americas / Ganfeng",
    "status": "producing",
    "significance": "One of Argentina's largest lithium brine projects. Recently commenced production.",
    "openPitOrUnderground": "in-situ"
  },
  {
    "id": "silver-peak",
    "name": "Silver Peak",
    "lat": 37.75,
    "lon": -117.65,
    "mineral": "Lithium",
    "country": "USA",
    "operator": "Albemarle",
    "status": "producing",
    "significance": "Only active US lithium mine. Nevada brine operation since 1966.",
    "openPitOrUnderground": "in-situ"
  },
  {
    "id": "thacker-pass",
    "name": "Thacker Pass",
    "lat": 41.85,
    "lon": -118.15,
    "mineral": "Lithium",
    "country": "USA",
    "operator": "Lithium Americas",
    "status": "development",
    "significance": "Largest known lithium deposit in the US. Under development in Nevada.",
    "openPitOrUnderground": "open-pit"
  },
  {
    "id": "manono",
    "name": "Manono",
    "lat": -7.3,
    "lon": 27.41,
    "mineral": "Lithium",
    "country": "DRC",
    "operator": "AVZ Minerals",
    "status": "development",
    "significance": "World's largest hard-rock lithium deposit. DRC asset under development.",
    "openPitOrUnderground": "open-pit"
  },
  {
    "id": "mutanda",
    "name": "Mutanda",
    "lat": -10.78,
    "lon": 25.8,
    "mineral": "Cobalt",
    "country": "DRC",
    "operator": "Glencore",
    "status": "producing",
    "significance": "World's largest cobalt mine. ~25kt Co/yr when at full capacity.",
    "productionRank": "World #1 cobalt mine",
    "openPitOrUnderground": "open-pit"
  },
  {
    "id": "tenke-fungurume",
    "name": "Tenke Fungurume",
    "lat": -10.61,
    "lon": 26.16,
    "mineral": "Cobalt",
    "country": "DRC",
    "operator": "CMOC",
    "status": "producing",
    "significance": "Major cobalt-copper producer. Chinese-owned. ~17kt Co/yr.",
    "openPitOrUnderground": "open-pit"
  },
  {
    "id": "kamoto",
    "name": "Kamoto (KOV)",
    "lat": -10.87,
    "lon": 25.55,
    "mineral": "Cobalt",
    "country": "DRC",
    "operator": "Glencore / Katanga Mining",
    "status": "producing",
    "significance": "Major DRC cobalt-copper underground mine.",
    "openPitOrUnderground": "underground"
  },
  {
    "id": "bayan-obo",
    "name": "Bayan Obo",
    "lat": 41.76,
    "lon": 109.95,
    "mineral": "Rare Earths",
    "country": "China",
    "operator": "China Northern Rare Earth Group",
    "status": "producing",
    "significance": "World's largest rare earth mine. ~45% of global REE production from this single site.",
    "productionRank": "World #1 REE mine",
    "openPitOrUnderground": "open-pit"
  },
  {
    "id": "mountain-pass",
    "name": "Mountain Pass",
    "lat": 35.47,
    "lon": -115.53,
    "mineral": "Rare Earths",
    "country": "USA",
    "operator": "MP Materials",
    "status": "producing",
    "significance": "Only significant rare earth mine and processor in the US. Strategic national asset.",
    "productionRank": "US #1 REE mine",
    "openPitOrUnderground": "open-pit"
  },
  {
    "id": "mount-weld",
    "name": "Mount Weld",
    "lat": -28.86,
    "lon": 122.17,
    "mineral": "Rare Earths",
    "country": "Australia",
    "operator": "Lynas Rare Earths",
    "status": "producing",
    "significance": "Highest-grade rare earth deposit outside China. Key non-Chinese REE source.",
    "productionRank": "World #2 REE mine",
    "openPitOrUnderground": "open-pit"
  },
  {
    "id": "southern-ion-adsorption",
    "name": "Southern China REE",
    "lat": 25.85,
    "lon": 114.93,
    "mineral": "Rare Earths",
    "country": "China",
    "operator": "Multiple Chinese operators",
    "status": "producing",
    "significance": "Jiangxi/Guangdong ion-adsorption clay deposits. Key source of heavy rare earths (dysprosium, terbium) critical for EV motors.",
    "openPitOrUnderground": "open-pit"
  },
  {
    "id": "kvanefjeld",
    "name": "Kvanefjeld",
    "lat": 60.96,
    "lon": -47,
    "mineral": "Rare Earths",
    "country": "Greenland",
    "operator": "Energy Transition Minerals",
    "status": "exploration",
    "significance": "World-class REE + uranium deposit in Greenland. Subject to Greenland political debate."
  },
  {
    "id": "weda-bay",
    "name": "Weda Bay / Halmahera",
    "lat": 0.47,
    "lon": 127.94,
    "mineral": "Nickel",
    "country": "Indonesia",
    "operator": "Tsingshan / Eramet",
    "status": "producing",
    "significance": "Largest nickel pig iron (NPI) production hub. Core of Indonesia's nickel dominance.",
    "productionRank": "Indonesia nickel #1 region",
    "openPitOrUnderground": "open-pit"
  },
  {
    "id": "morowali",
    "name": "Morowali Industrial Park",
    "lat": -2.1,
    "lon": 121.9,
    "mineral": "Nickel",
    "country": "Indonesia",
    "operator": "Tsingshan Group (various)",
    "status": "producing",
    "significance": "Largest integrated nickel production hub globally. Drives ~50% of world's battery-grade nickel.",
    "openPitOrUnderground": "open-pit"
  },
  {
    "id": "norilsk-mine",
    "name": "Norilsk Complex",
    "lat": 69.33,
    "lon": 88.21,
    "mineral": "Nickel",
    "country": "Russia",
    "operator": "Nornickel",
    "status": "producing",
    "significance": "World's largest palladium mine and top nickel producer. Arctic Siberian site.",
    "productionRank": "World #1 palladium, #2 nickel",
    "openPitOrUnderground": "underground"
  },
  {
    "id": "voiseys-bay",
    "name": "Voisey's Bay",
    "lat": 56.37,
    "lon": -62.08,
    "mineral": "Nickel",
    "country": "Canada",
    "operator": "Vale",
    "status": "producing",
    "significance": "High-grade nickel-cobalt-copper mine in Labrador. Strategic Canadian deposit.",
    "openPitOrUnderground": "underground"
  },
  {
    "id": "goro",
    "name": "Goro (Vale Nouvelle-Calédonie)",
    "lat": -22.27,
    "lon": 167,
    "mineral": "Nickel",
    "country": "New Caledonia",
    "operator": "Prony Resources",
    "status": "producing",
    "significance": "Major laterite nickel operation. Battery-grade nickel and cobalt production.",
    "openPitOrUnderground": "open-pit"
  },
  {
    "id": "taganito",
    "name": "Taganito",
    "lat": 9.15,
    "lon": 125.77,
    "mineral": "Nickel",
    "country": "Philippines",
    "operator": "Sumitomo / DMCI",
    "status": "producing",
    "significance": "Key Philippine nickel laterite mine. Major Japanese nickel supply source.",
    "openPitOrUnderground": "open-pit"
  },
  {
    "id": "mogalakwena",
    "name": "Mogalakwena",
    "lat": -24.05,
    "lon": 28.76,
    "mineral": "Platinum",
    "country": "South Africa",
    "operator": "Anglo American Platinum",
    "status": "producing",
    "significance": "World's largest open-pit platinum mine. Bushveld Igneous Complex.",
    "productionRank": "World #1 open-pit PGM mine",
    "openPitOrUnderground": "open-pit"
  },
  {
    "id": "marikana",
    "name": "Marikana / Rustenburg",
    "lat": -25.68,
    "lon": 27.38,
    "mineral": "Platinum",
    "country": "South Africa",
    "operator": "Sibanye-Stillwater",
    "status": "producing",
    "significance": "Major Bushveld Complex platinum operations. Historically significant labor site.",
    "openPitOrUnderground": "underground"
  },
  {
    "id": "zimplats",
    "name": "Zimplats",
    "lat": -18.12,
    "lon": 30.45,
    "mineral": "Platinum",
    "country": "Zimbabwe",
    "operator": "Impala Platinum",
    "status": "producing",
    "significance": "Zimbabwe's largest mining company. World's third-largest PGM producer.",
    "openPitOrUnderground": "both"
  },
  {
    "id": "stillwater",
    "name": "Stillwater",
    "lat": 45.37,
    "lon": -109.93,
    "mineral": "Palladium",
    "country": "USA",
    "operator": "Sibanye-Stillwater",
    "status": "producing",
    "significance": "Only significant PGM mine in North America. Primary US palladium source.",
    "productionRank": "North America #1 PGM",
    "openPitOrUnderground": "underground"
  },
  {
    "id": "pilbara",
    "name": "Pilbara Iron Ore (BHP)",
    "lat": -22.5,
    "lon": 119,
    "mineral": "Iron Ore",
    "country": "Australia",
    "operator": "BHP",
    "status": "producing",
    "significance": "BHP's Pilbara hub — world's most productive iron ore mining region. ~280Mt/yr.",
    "productionRank": "BHP Pilbara iron ore hub",
    "openPitOrUnderground": "open-pit"
  },
  {
    "id": "pilbara-rio",
    "name": "Pilbara Iron Ore (Rio Tinto)",
    "lat": -22.7,
    "lon": 118.6,
    "mineral": "Iron Ore",
    "country": "Australia",
    "operator": "Rio Tinto",
    "status": "producing",
    "significance": "Rio Tinto's Pilbara operations — 16 mines feeding 4 port facilities. ~330Mt/yr.",
    "productionRank": "World #1 iron ore producer (Rio)",
    "openPitOrUnderground": "open-pit"
  },
  {
    "id": "carajas",
    "name": "Carajás",
    "lat": -5.83,
    "lon": -50.61,
    "mineral": "Iron Ore",
    "country": "Brazil",
    "operator": "Vale",
    "status": "producing",
    "significance": "World's largest iron ore mine by proven reserves. Highest grade iron ore (~67% Fe).",
    "productionRank": "World #1 iron ore reserve",
    "openPitOrUnderground": "open-pit",
    "productionCapacity": "~180Mt/yr"
  },
  {
    "id": "sishen",
    "name": "Sishen",
    "lat": -27.79,
    "lon": 22.98,
    "mineral": "Iron Ore",
    "country": "South Africa",
    "operator": "Kumba Iron Ore (Anglo American)",
    "status": "producing",
    "significance": "Africa's largest iron ore mine. Major export source for European and Asian steel mills.",
    "openPitOrUnderground": "open-pit"
  },
  {
    "id": "kiruna",
    "name": "Kiruna",
    "lat": 67.85,
    "lon": 20.32,
    "mineral": "Iron Ore",
    "country": "Sweden",
    "operator": "LKAB",
    "status": "producing",
    "significance": "Europe's largest iron ore mine. Undergoing city relocation due to mine expansion.",
    "openPitOrUnderground": "underground"
  },
  {
    "id": "mcarthur-river",
    "name": "McArthur River",
    "lat": 57.76,
    "lon": -105.03,
    "mineral": "Uranium",
    "country": "Canada",
    "operator": "Cameco",
    "status": "producing",
    "significance": "World's highest-grade uranium mine. 25x average uranium ore grade. Saskatchewan, Canada.",
    "productionRank": "World #1 by grade",
    "openPitOrUnderground": "underground"
  },
  {
    "id": "cigar-lake",
    "name": "Cigar Lake",
    "lat": 57.67,
    "lon": -105.61,
    "mineral": "Uranium",
    "country": "Canada",
    "operator": "Cameco / Orano",
    "status": "producing",
    "significance": "World's largest high-grade uranium deposit currently in production.",
    "productionRank": "World #1 by production volume (high-grade)",
    "openPitOrUnderground": "underground"
  },
  {
    "id": "kazakh-isu",
    "name": "Kazakhstan ISL Fields",
    "lat": 43.6,
    "lon": 65.4,
    "mineral": "Uranium",
    "country": "Kazakhstan",
    "operator": "Kazatomprom",
    "status": "producing",
    "significance": "Cluster of in-situ leaching uranium operations. Kazakhstan produces ~40% of world supply.",
    "productionRank": "World #1 uranium producer country",
    "openPitOrUnderground": "in-situ"
  },
  {
    "id": "olympic-dam",
    "name": "Olympic Dam",
    "lat": -30.44,
    "lon": 136.89,
    "mineral": "Uranium",
    "country": "Australia",
    "operator": "BHP",
    "status": "producing",
    "significance": "World's largest known uranium ore body. Also produces copper, gold, silver.",
    "productionRank": "World #1 uranium ore body",
    "openPitOrUnderground": "underground"
  },
  {
    "id": "rossing",
    "name": "Rössing",
    "lat": -22.45,
    "lon": 14.99,
    "mineral": "Uranium",
    "country": "Namibia",
    "operator": "China National Uranium Corp",
    "status": "producing",
    "significance": "One of the world's largest open-pit uranium mines. Chinese-owned since 2019.",
    "openPitOrUnderground": "open-pit"
  },
  {
    "id": "husab",
    "name": "Husab",
    "lat": -22.46,
    "lon": 15.18,
    "mineral": "Uranium",
    "country": "Namibia",
    "operator": "China General Nuclear Power",
    "status": "producing",
    "significance": "Second-largest uranium mine globally by production. 100% Chinese-owned.",
    "productionRank": "World #2 uranium mine",
    "openPitOrUnderground": "open-pit"
  }
];
export default MINING_SITES;
